'use strict';
const {openBrowser}=require('./plan_import/support/PlanningBrowser.cjs');
const cfg=JSON.parse(process.env.SISCO_PLANNING_FIXTURE||'{}');
if(!/^http:\/\/127\.0\.0\.1:\d+$/.test(cfg.url)||!cfg.plan||!cfg.token)throw Error('Se requiere instalación temporal.');
let checks=0;
const check=(ok,message)=>{if(!ok)throw Error(message);checks++;console.log('OK | navegador | '+message);};
(async()=>{
 const browser=await openBrowser();const {evaluate,wait,navigate}=browser;
 try{
  await navigate(cfg.url+'/mvc/views/auth/login.php');
  await evaluate(`document.querySelector('[name="usuario"]').value='pdf_test';document.querySelector('[name="password"]').value='Temporal123';document.querySelector('form').requestSubmit();`);
  await wait(`/dashboard\.php/.test(location.pathname)`);check(true,'login real');
  await navigate(cfg.url+'/mvc/views/planificacion/import_preview.php?token='+cfg.token);
  await wait(`!![...document.querySelectorAll('button')].find(b=>b.textContent.includes('Agregar fechas confirmadas'))`);
  await evaluate(`[...document.querySelectorAll('button')].find(b=>b.textContent.includes('Agregar fechas confirmadas')).click()`);
  check(await evaluate(`[...document.querySelectorAll('#plan-import-preview-root input[type=date]')].every(input=>input.value==='') && document.querySelectorAll('#plan-import-preview-root input[type=date]').length===2`),'preview: fechas nuevas vacías');
  await evaluate(`[...document.querySelectorAll('button')].find(b=>b.textContent==='Guardar correcciones').click()`);
  await wait(`document.body.innerText.includes('Seleccione inicio y fin para todas')`);check(true,'preview rechaza guardar fechas vacías');
  await navigate(cfg.url+'/mvc/views/planificacion/editor.php?id_plan='+cfg.plan);
  await wait(`document.querySelectorAll('[data-programacion-tema]').length===18`);
  check(await evaluate(`document.querySelector('#plan-programacion-resumen').textContent.includes('18 pendientes') && document.querySelector('#btn-estado-plan').disabled`),'18 temas pendientes bloquean publicar');
  check(await evaluate(`[...document.querySelectorAll('[data-programacion-inicio],[data-programacion-fin]')].every(input=>input.value==='')`),'periodo fuente no inventa fechas');
  check(await evaluate(`document.querySelector('#plan-programacion-filas').textContent.includes('Febrero')`),'periodo fuente visible');
  await evaluate(`document.querySelector('[data-programacion-inicio]').value='2026-10-05';document.querySelector('#form-programacion-anual').requestSubmit()`);
  await wait(`document.querySelector('#mensaje-programacion-anual').textContent.includes('Seleccione inicio y fin')`);check(true,'programación parcial no se guarda');
  await evaluate(`document.querySelectorAll('[data-programacion-tema]').forEach((row,index)=>{const date=new Date(Date.UTC(2026,9,5+index)).toISOString().slice(0,10);row.querySelector('[data-programacion-inicio]').value=date;row.querySelector('[data-programacion-fin]').value=date;row.querySelector('[data-programacion-horas]').value='1';});document.querySelector('#form-programacion-anual').dispatchEvent(new Event('input',{bubbles:true}));`);
  check(await evaluate(`document.querySelector('#btn-estado-plan').disabled`),'cambios sin guardar bloquean publicar');
  await evaluate(`document.querySelector('#form-programacion-anual').requestSubmit()`);
  await wait(`document.querySelector('#plan-programacion-estado').textContent==='LISTO PARA PUBLICAR'`);
  check(await evaluate(`document.querySelector('#plan-programacion-resumen').textContent.includes('18 programados') && !document.querySelector('#btn-estado-plan').disabled`),'guardado anual completo: 18/18 y listo para publicar');
  await evaluate(`document.querySelector('#btn-estado-plan').click()`);await wait(`document.querySelector('#plan-editor-contexto').textContent.includes('PUBLICADO')`);check(true,'publicación desde UI');
  const marks=await evaluate(`(async()=>{const mark=async(tipo,ci)=>{const form=new URLSearchParams({tipo_persona:tipo,ci,id_aula:${cfg.aula},estado:'PRESENTE'});return (await fetch('/src/api/Gateway/registrar_asistencia.php',{method:'POST',headers:{'X-GATEWAY-KEY':${JSON.stringify(process.env.SISCO_TEST_GATEWAY_KEY)}},body:form})).json();};const professor=await mark('profesor',${JSON.stringify(cfg.teacher)});const students=[];for(const ci of ${JSON.stringify(cfg.students.slice(0,3))})students.push(await mark('estudiante',ci));return{professor,students};})()`);
  check(marks.professor.ok && marks.students.every(mark=>mark.ok),'Gateway HTTP abre clase y registra tres alumnos');
  const idClass=marks.professor.data.id_clase;
  await navigate(cfg.url+'/mvc/views/informes/diario.php');
  await wait(`document.querySelector('#informe-asignacion').options.length>1`);
  await evaluate(`document.querySelector('#informe-fecha').value='2026-10-05';document.querySelector('#informe-fecha').dispatchEvent(new Event('change',{bubbles:true}))`);
  await wait(`!!document.querySelector('[data-clase="${idClass}"]')`);
  await evaluate(`document.querySelector('[data-clase="${idClass}"]').click()`);
  await wait(`!!document.querySelector('[data-informe-contenido-tema]')`);
  check(await evaluate(`document.querySelector('[data-informe-contenido-tema]').textContent==='Contenido <seguro> del tema temporal' && !document.querySelector('[data-informe-contenido-tema] seguro')`),'contenido del tema debajo del título, escapado como texto');
  check(await evaluate(`document.querySelectorAll('#informe-contenido tbody tr').length===5 && document.querySelector('.report-attendance-summary').textContent.includes('3 presentes') && document.querySelector('.report-attendance-summary').textContent.includes('2 ausentes')`),'informe visible: cinco alumnos, tres presentes y dos ausentes');
  await navigate(cfg.url+'/mvc/views/planificacion/editor.php?id_plan='+cfg.plan);await wait(`document.querySelectorAll('[data-programacion-tema]').length===18`);
  await evaluate(`document.querySelector('#btn-archivar-plan').click()`);
  await wait(`document.querySelector('#plan-programacion-estado').textContent.includes('SOLO LECTURA')`);
  check(await evaluate(`[...document.querySelectorAll('[data-planificacion-editor] input,[data-planificacion-editor] textarea,[data-planificacion-editor] select,[data-planificacion-editor] button')].every(control=>control.disabled)`),'archivado: controles de mutación deshabilitados');
  check(browser.errors.length===0,'sin excepciones JavaScript');
  console.log(`PlanningAnnualHeadlessTest: ${checks} PASS; 0 FAIL`);
 }finally{await browser.close();}
})().catch(error=>{console.error(error.message);process.exitCode=1;});
