<?php
declare(strict_types=1);
require_once __DIR__.'/../support/TestEnvironment.php';
function e2eHttp(PlanImportTestEnvironment $env,string $cookie,string $path,string $method='GET',mixed $body=null,?string $csrf=null):array{
    $curl=curl_init($env->url.$path);$headers=[];if($csrf)$headers[]='X-CSRF-Token: '.$csrf;if(is_string($body))$headers[]='Content-Type: application/json';curl_setopt_array($curl,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_CUSTOMREQUEST=>$method,CURLOPT_COOKIEJAR=>$cookie,CURLOPT_COOKIEFILE=>$cookie,CURLOPT_HTTPHEADER=>$headers,CURLOPT_TIMEOUT=>45]);if($body!==null)curl_setopt($curl,CURLOPT_POSTFIELDS,$body);$raw=(string)curl_exec($curl);$status=(int)curl_getinfo($curl,CURLINFO_RESPONSE_CODE);$location=(string)curl_getinfo($curl,CURLINFO_REDIRECT_URL);curl_close($curl);$json=null;try{$json=json_decode($raw,true,512,JSON_THROW_ON_ERROR);}catch(JsonException){}return compact('status','raw','json','location');
}
function e2eCounts(array $plan):array{$r=['unidades'=>count($plan['unidades']),'capacidades'=>0,'temas'=>0,'indicadores'=>0];foreach($plan['unidades'] as $u){$r['capacidades']+=count($u['capacidades']);foreach($u['capacidades'] as $c){$r['temas']+=count($c['temas']);foreach($c['temas'] as $t)$r['indicadores']+=count($t['indicadores']);}}return$r;}
function assertAdminFinance3(array $canonical,array $loaded,string $expectedPath):void{
    $expected=json_decode(file_get_contents($expectedPath),true,64,JSON_THROW_ON_ERROR);if(e2eCounts($canonical)!==['unidades'=>6,'capacidades'=>6,'temas'=>18,'indicadores'=>18])throw new RuntimeException('AdministraciÃ³n Financiera 3: conteos');
    foreach($expected['metadata'] as $key=>$value){$loadedKey=['institucion'=>'institucion_fuente','materia'=>'materia_fuente','profesor'=>'profesor_fuente','curso'=>'curso_fuente','turno'=>'turno_fuente','anio'=>'anio_fuente'][$key]??null;if($loadedKey&&$loaded[$loadedKey]!=$value)throw new RuntimeException('AdministraciÃ³n Financiera 3: metadata.'.$key);}
    if(array_column($loaded['unidades'],'codigo')!==$expected['unit_codes']||array_column($loaded['unidades'],'nombre')!==$expected['unit_names'])throw new RuntimeException('AdministraciÃ³n Financiera 3: unidades/cÃ³digos');
    if(array_map('floatval',array_column($loaded['unidades'],'horas_catedra'))!==array_map('floatval',$expected['unit_hours'])||array_column($loaded['unidades'],'proceso_texto')!==$expected['unit_processes'])throw new RuntimeException('AdministraciÃ³n Financiera 3: HC/proceso');
    $topicCodes=[];$procedures=[];$instruments=[];foreach($loaded['unidades'] as $u){foreach($u['capacidades'] as $c)foreach($c['temas'] as $t)$topicCodes[]=$t['codigo'];$first=$u['capacidades'][0]['temas'][0];$procedures[]=array_map(static fn(array $r):string=>$r['texto_fuente']??$r['nombre'],$first['procedimientos']);$instruments[]=array_map(static fn(array $r):string=>$r['texto_fuente']??$r['nombre'],$first['instrumentos']);}if($topicCodes!==$expected['topic_codes']||$procedures!==$expected['procedures_by_unit']||$instruments!==$expected['instruments_by_unit'])throw new RuntimeException('AdministraciÃ³n Financiera 3: temas/evaluaciÃ³n');
}
$env=new PlanImportTestEnvironment();$passed=0;
try{
    $root=dirname(__DIR__,3);$cookie=$env->directory.'/browser-cookies.txt';$login=e2eHttp($env,$cookie,'/src/api/login.php','POST',['usuario'=>'pdf_test','password'=>'Temporal123']);if($login['status']!==302||!str_contains($login['location'],'dashboard.php'))throw new RuntimeException('Login profesor E2E');$index=e2eHttp($env,$cookie,'/mvc/views/planificacion/index.php');if($index['status']!==200||!preg_match('/"csrf":"([a-f0-9]{64})"/',$index['raw'],$match))throw new RuntimeException('Entrada de importaciÃ³n E2E');$csrf=$match[1];
    $base=$env->db->query('SELECT id_profesor,id_grado FROM asignacion_docente WHERE id_asignacion='.$env->assignment)->fetch(PDO::FETCH_ASSOC);$assignments=[$env->assignment];for($n=1;$n<4;$n++){$matter=$env->insert('INSERT INTO materias (nombre,activo) VALUES (?,1)',['E2E PDF '.$n]);$assignments[]=$env->insert('INSERT INTO asignacion_docente (id_profesor,id_materia,id_grado,carga_horaria,anio_lectivo,activo) VALUES (?,?,?,4,2026,1)',[(int)$base['id_profesor'],$matter,(int)$base['id_grado']]);}
    $fixtures=glob($root.'/test/fixtures/planes/*.pdf');sort($fixtures,SORT_STRING);foreach($fixtures as $indexNumber=>$pdf){$upload=e2eHttp($env,$cookie,'/src/api/Planificacion/importar_plan_pdf.php','POST',['id_asignacion'=>$assignments[$indexNumber],'anio'=>2026,'pdf'=>new CURLFile($pdf,'application/pdf',basename($pdf))],$csrf);if($upload['status']!==201)throw new RuntimeException(basename($pdf).' upload: '.$upload['raw']);$data=$upload['json']['data'];$original=$data['plan'];$data['plan']['metadata']['competencia_especifica']=trim((string)$data['plan']['metadata']['competencia_especifica']).' [correcciÃ³n E2E '.($indexNumber+1).']';$decisions=array_map(static fn(array $s):array=>['kind'=>$s['kind'],'text'=>$s['text'],'action'=>$s['suggested_id']?'existing':'create','id'=>$s['suggested_id']?:null],$data['suggestions']);$save=e2eHttp($env,$cookie,'/src/api/Planificacion/preview_importacion.php','PUT',json_encode(['token'=>$data['token'],'plan'=>$data['plan'],'decisions'=>$decisions,'programming'=>[]]),$csrf);if($save['status']!==200||!$save['json']['data']['readiness']['can_confirm'])throw new RuntimeException(basename($pdf).' preview: '.$save['raw']);$confirm=e2eHttp($env,$cookie,'/src/api/Planificacion/confirmar_importacion.php','POST',json_encode(['token'=>$data['token']]),$csrf);if($confirm['status']!==201)throw new RuntimeException(basename($pdf).' confirm: '.$confirm['raw']);$id=(int)$confirm['json']['data']['id_plan'];
        $editor=e2eHttp($env,$cookie,'/mvc/views/planificacion/editor.php?id_plan='.$id);if($editor['status']!==200||!str_contains($editor['raw'],'data-planificacion-editor'))throw new RuntimeException(basename($pdf).' abrir editor');$open=e2eHttp($env,$cookie,'/src/api/Planificacion/planes.php?id_plan='.$id);$loaded=$open['json']['data'];if(!str_contains((string)$loaded['competencia_especifica'],'[correcciÃ³n E2E'))throw new RuntimeException(basename($pdf).' correcciÃ³n no persistida');if(str_contains(basename($pdf),'tercer curso - BTI'))assertAdminFinance3($original,$loaded,$root.'/test/plan_parser_poc/expected/admin_financiera_3.expected.json');
        $update=['accion'=>'actualizar','id_plan'=>$id,'competencia_general'=>$loaded['competencia_general'],'competencia_especifica'=>$loaded['competencia_especifica'],'observaciones'=>'Editado desde PlanificaciÃ³n normal E2E '.($indexNumber+1),'institucion_fuente'=>$loaded['institucion_fuente'],'materia_fuente'=>$loaded['materia_fuente'],'profesor_fuente'=>$loaded['profesor_fuente'],'curso_fuente'=>$loaded['curso_fuente'],'turno_fuente'=>$loaded['turno_fuente'],'anio_fuente'=>$loaded['anio_fuente'],'dias_clase_fuente'=>$loaded['dias_clase_fuente']];$savedPlan=e2eHttp($env,$cookie,'/src/api/Planificacion/planes.php','POST',json_encode($update));if($savedPlan['status']!==200)throw new RuntimeException(basename($pdf).' editar plan normal');$u=$loaded['unidades'][0];$unitUpdate=['accion'=>'guardar','tipo'=>'unidad','id_unidad'=>$u['id_unidad'],'id_plan'=>$id,'codigo'=>$u['codigo'],'nombre'=>$u['nombre'],'descripcion'=>'Unidad reeditada E2E '.($indexNumber+1),'horas_catedra'=>$u['horas_catedra'],'tiempo_texto'=>$u['tiempo_texto'],'proceso_texto'=>$u['proceso_texto'],'proceso_inicio'=>$u['proceso_inicio'],'proceso_fin'=>$u['proceso_fin'],'area_transversal'=>$u['area_transversal'],'metodologia'=>$u['metodologia'],'medios_verificacion'=>$u['medios_verificacion']];$savedUnit=e2eHttp($env,$cookie,'/src/api/Planificacion/estructura.php','POST',json_encode($unitUpdate));if($savedUnit['status']!==200)throw new RuntimeException(basename($pdf).' editar unidad normal');$reopen=e2eHttp($env,$cookie,'/src/api/Planificacion/planes.php?id_plan='.$id);if($reopen['json']['data']['observaciones']!==$update['observaciones']||$reopen['json']['data']['unidades'][0]['descripcion']!==$unitUpdate['descripcion'])throw new RuntimeException(basename($pdf).' reapertura final');$passed++;echo 'PASS E2E | '.basename($pdf).PHP_EOL;
    }
    if($passed!==4||(int)$env->db->query('SELECT COUNT(*) FROM planes_anuales')->fetchColumn()!==4)throw new RuntimeException('E2E '.$passed.'/4');
}finally{$env->close();}
echo "OK | FullE2ETest | 4/4 login -> importar -> preview/corregir -> confirmar -> abrir/editar/guardar/reabrir; BD temporal eliminada\n";
