<?php
declare(strict_types=1);
require_once __DIR__.'/../support/TestEnvironment.php';
function securityCurl(PlanImportTestEnvironment $env,string $endpoint,string $session,string $csrf,string $method='GET',?string $body=null):CurlHandle{
    $curl=curl_init($env->url.'/src/api/Planificacion/'.$endpoint);$headers=['X-CSRF-Token: '.$csrf];if($body!==null)$headers[]='Content-Type: application/json';curl_setopt_array($curl,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_CUSTOMREQUEST=>$method,CURLOPT_HTTPHEADER=>$headers,CURLOPT_COOKIE=>'PHPSESSID='.$session,CURLOPT_TIMEOUT=>30]);if($body!==null)curl_setopt($curl,CURLOPT_POSTFIELDS,$body);return $curl;
}
$env=new PlanImportTestEnvironment();
try{
    $pdf=glob(dirname(__DIR__,3).'/test/fixtures/planes/*tercer curso*Administracion financiera.pdf')[0];$uploadBody=['id_asignacion'=>$env->assignment,'anio'=>2026,'pdf'=>new CURLFile($pdf,'application/pdf',basename($pdf))];
    $foreign=$env->request('importar_plan_pdf.php','POST',$uploadBody);$foreignToken=$foreign['json']['data']['token'];
    $otherUser=$env->insert("INSERT INTO usuarios (nombre,apellido,usuario,email,celular,password,rol,activo) VALUES ('Otro','User','security_other','security_other@test.local',981234568,?,'Profesor',1)",[password_hash('Temporal123',PASSWORD_DEFAULT)]);$otherSession=bin2hex(random_bytes(16));$otherCsrf=bin2hex(random_bytes(32));session_save_path($env->directory.'/sessions');session_id($otherSession);session_start();$_SESSION=['id_usuario'=>$otherUser,'rol'=>'Profesor','plan_import_csrf'=>$otherCsrf];session_write_close();
    $curl=securityCurl($env,'preview_importacion.php?token='.$foreignToken,$otherSession,$otherCsrf);$raw=curl_exec($curl);$status=curl_getinfo($curl,CURLINFO_RESPONSE_CODE);curl_close($curl);if($status!==403||json_decode($raw,true)['error_type']!=='TOKEN_FORBIDDEN')throw new RuntimeException('Token ajeno');
    if($env->request('preview_importacion.php?token=../../'.$foreignToken)['status']!==422)throw new RuntimeException('Path traversal token');

    $expired=$env->request('importar_plan_pdf.php','POST',$uploadBody);$expiredToken=$expired['json']['data']['token'];$statePath=$env->directory.'-storage/'.$expiredToken.'/state.json';$state=json_decode(file_get_contents($statePath),true);$state['expires']=time()-1;file_put_contents($statePath,json_encode($state,JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR),LOCK_EX);$expiredResult=$env->request('preview_importacion.php?token='.$expiredToken);if($expiredResult['status']!==410||$expiredResult['json']['error_type']!=='TOKEN_EXPIRED')throw new RuntimeException('Token expirado');

    $data=$foreign['json']['data'];$decisions=array_map(static fn(array $s):array=>['kind'=>$s['kind'],'text'=>$s['text'],'action'=>'create','id'=>null],$data['suggestions']);$saved=$env->request('preview_importacion.php','PUT',json_encode(['token'=>$foreignToken,'plan'=>$data['plan'],'decisions'=>$decisions,'programming'=>[]]));if(!$saved['json']['data']['readiness']['can_confirm'])throw new RuntimeException('No listo para concurrencia');
    $payload=json_encode(['token'=>$foreignToken]);$multi=curl_multi_init();$handles=[securityCurl($env,'confirmar_importacion.php',$env->session,$env->csrf,'POST',$payload),securityCurl($env,'confirmar_importacion.php',$env->session,$env->csrf,'POST',$payload)];foreach($handles as $handle)curl_multi_add_handle($multi,$handle);do{$code=curl_multi_exec($multi,$running);if($running)curl_multi_select($multi,1.0);}while($running&&$code===CURLM_OK);$statuses=[];$ids=[];foreach($handles as $handle){$statuses[]=(int)curl_getinfo($handle,CURLINFO_RESPONSE_CODE);$json=json_decode(curl_multi_getcontent($handle),true);$ids[]=(int)($json['data']['id_plan']??0);curl_multi_remove_handle($multi,$handle);curl_close($handle);}curl_multi_close($multi);sort($statuses);if($statuses!==[200,201]||count(array_unique($ids))!==1||$ids[0]<1)throw new RuntimeException('Concurrencia/doble confirmaciÃ³n: '.json_encode([$statuses,$ids]));if((int)$env->db->query('SELECT COUNT(*) FROM planes_anuales')->fetchColumn()!==1)throw new RuntimeException('Concurrencia creÃ³ planes duplicados');
    $consumed=$env->request('preview_importacion.php?token='.$foreignToken);if($consumed['status']!==409||$consumed['json']['error_type']!=='TOKEN_CONSUMED')throw new RuntimeException('Token consumido');
    if($env->request('cancelar_importacion.php','DELETE',json_encode(['token'=>$foreignToken]))['status']!==409)throw new RuntimeException('CancelaciÃ³n de consumido');
    echo "OK | SecurityMatrixTest (token ajeno/expirado/consumido, traversal, CSRF heredado, concurrencia e idempotencia; un plan temporal)\n";
}finally{$env->close();}
