<?php
declare(strict_types=1);
require_once dirname(__DIR__,3).'/src/classes/PlanImport/bootstrap.php';
require_once dirname(__DIR__,3).'/src/classes/PlanificacionPedagogica.php';
require_once __DIR__.'/../support/TestEnvironment.php';
require_once __DIR__.'/../support/CanonicalPlanRoundTripRepository.php';
use SiscoEdu\PlanImport\{PdfPlanImporter,PreviewValidator,PlanImportPersistence,CatalogMatcher};

function firstJsonDiff(mixed $expected,mixed $actual,string $path='$'):?string{
    if(gettype($expected)!==gettype($actual)&&!((is_int($expected)||is_float($expected))&&(is_int($actual)||is_float($actual))))return $path.' tipo esperado='.gettype($expected).' actual='.gettype($actual);
    if(is_array($expected)){if(array_keys($expected)!==array_keys($actual))return $path.' claves esperadas='.json_encode(array_keys($expected)).' actuales='.json_encode(array_keys($actual));foreach($expected as $key=>$value){$child=is_int($key)?$path.'['.$key.']':($path==='$'?$path.'.'.$key:$path.'.'.$key);$diff=firstJsonDiff($value,$actual[$key],$child);if($diff)return $diff;}return null;}
    return $expected==$actual?null:$path.' esperado='.json_encode($expected,JSON_UNESCAPED_UNICODE).' actual='.json_encode($actual,JSON_UNESCAPED_UNICODE);
}
function manualCanonicalAcademic(array $loaded):array{
    $units=[];foreach($loaded['unidades'] as $u){$unit=['orden'=>(int)$u['orden'],'codigo'=>$u['codigo'],'nombre'=>$u['nombre'],'descripcion'=>$u['descripcion'],'horas_catedra'=>$u['horas_catedra']===null?null:(float)$u['horas_catedra'],'tiempo_texto'=>$u['tiempo_texto'],'proceso_texto'=>$u['proceso_texto'],'area_transversal'=>$u['area_transversal'],'metodologia'=>$u['metodologia'],'medios_verificacion'=>$u['medios_verificacion'],'capacidades'=>[]];foreach($u['capacidades'] as $c){$capacity=['orden'=>(int)$c['orden'],'descripcion'=>$c['descripcion'],'proceso_desarrollo'=>$c['proceso_desarrollo'],'temas'=>[]];foreach($c['temas'] as $t){$topic=['orden'=>(int)$t['orden'],'codigo'=>$t['codigo'],'titulo'=>$t['titulo'],'contenido'=>$t['contenido'],'horas_catedra'=>$t['horas_catedra']===null?null:(float)$t['horas_catedra'],'tiempo_texto'=>$t['tiempo_texto'],'fecha_texto'=>$t['fecha_texto'],'indicadores'=>[],'procedimientos_evaluativos'=>array_map(static fn(array $r):string=>$r['texto_fuente']??$r['nombre'],$t['procedimientos']),'instrumentos_evaluativos'=>array_map(static fn(array $r):string=>$r['texto_fuente']??$r['nombre'],$t['instrumentos'])];foreach($t['indicadores'] as $i)$topic['indicadores'][]=['orden'=>(int)$i['orden'],'codigo'=>$i['codigo'],'descripcion'=>$i['descripcion'],'check'=>null];$capacity['temas'][]=$topic;}$unit['capacidades'][]=$capacity;}$units[]=$unit;}
    return ['metadata'=>['institucion'=>$loaded['institucion_fuente'],'materia'=>$loaded['materia_fuente'],'profesor'=>$loaded['profesor_fuente'],'curso'=>$loaded['curso_fuente'],'turno'=>$loaded['turno_fuente'],'anio'=>$loaded['anio_fuente']===null?null:(int)$loaded['anio_fuente'],'dias_clase'=>$loaded['dias_clase_fuente'],'competencia_general'=>$loaded['competencia_general'],'competencia_especifica'=>$loaded['competencia_especifica']],'unidades'=>$units];
}
$env=new PlanImportTestEnvironment();
try{
    $root=dirname(__DIR__,3);if(trim((string)getenv('SISCO_PDFTOTEXT_PATH'))==='')putenv('SISCO_PDFTOTEXT_PATH=C:\\Program Files\\Git\\mingw64\\bin\\pdftotext.exe');$contracts=json_decode(file_get_contents(__DIR__.'/../expected/contracts.json'),true,32,JSON_THROW_ON_ERROR);$importer=PdfPlanImporter::fromConfig(require $root.'/src/config/plan_import.php');
    $row=$env->db->query('SELECT id_profesor,id_grado FROM asignacion_docente WHERE id_asignacion='.$env->assignment)->fetch(PDO::FETCH_ASSOC);$assignments=[$env->assignment];for($n=1;$n<4;$n++){$matter=$env->insert('INSERT INTO materias (nombre,activo) VALUES (?,1)',['PIPELINE '.$n]);$assignments[]=$env->insert('INSERT INTO asignacion_docente (id_profesor,id_materia,id_grado,carga_horaria,anio_lectivo,activo) VALUES (?,?,?,4,2026,1)',[(int)$row['id_profesor'],$matter,(int)$row['id_grado']]);}
    $passed=0;foreach($contracts as $filename=>$relative){$pdf=$root.'/test/fixtures/planes/'.$filename;$expected=json_decode(file_get_contents(__DIR__.'/../expected/'.$relative),true,512,JSON_THROW_ON_ERROR);$plan=$importer->import($pdf,true);
        $expectedContract=['source'=>['filename'=>$expected['source']['filename'],'format'=>$expected['source']['format'],'sha256'=>$expected['source']['sha256'],'pages'=>$expected['source']['pages']],'metadata'=>$expected['metadata'],'unidades'=>$expected['unidades'],'warnings'=>$expected['warnings'],'confidence'=>$expected['confidence']];$actualContract=['source'=>array_intersect_key($plan['source'],$expectedContract['source']),'metadata'=>$plan['metadata'],'unidades'=>$plan['unidades'],'warnings'=>$plan['warnings'],'confidence'=>$plan['confidence']];if($diff=firstJsonDiff($expectedContract,$actualContract))throw new RuntimeException($filename.' parser/expected: '.$diff);
        $state=['plan'=>$plan,'parser_warnings'=>$plan['warnings']];$plan=(new PreviewValidator())->validate($plan,$state);
        $catalogs=['procedimientos'=>$env->db->query('SELECT id_procedimiento id,nombre FROM procedimientos_evaluativos WHERE activo=1')->fetchAll(PDO::FETCH_ASSOC),'instrumentos'=>$env->db->query('SELECT id_instrumento id,nombre FROM instrumentos_evaluativos WHERE activo=1')->fetchAll(PDO::FETCH_ASSOC)];$suggestions=(new CatalogMatcher())->suggestions($plan,$catalogs);$decisions=array_map(static fn(array $s):array=>['kind'=>$s['kind'],'text'=>$s['text'],'action'=>$s['suggested_id']?'existing':'create','id'=>$s['suggested_id']?:null],$suggestions);
        $env->db->beginTransaction();$id=(new PlanImportPersistence($env->db))->persist($plan,$assignments[$passed],2026,$env->user,$decisions,[]);$env->db->commit();$rebuilt=(new CanonicalPlanRoundTripRepository($env->db))->reconstruct($id);if($diff=firstJsonDiff($plan,$rebuilt))throw new RuntimeException($filename.' round-trip: '.$diff);
        $loaded=(new PlanificacionPedagogica($env->db,['id_usuario'=>$env->user,'rol'=>'Profesor']))->obtenerPlan($id);if($diff=firstJsonDiff(['metadata'=>$plan['metadata'],'unidades'=>$plan['unidades']],manualCanonicalAcademic($loaded)))throw new RuntimeException($filename.' lectura normal: '.$diff);$passed++;echo 'PASS PIPELINE | '.$filename.PHP_EOL;
    }if($passed!==4)throw new RuntimeException('Resultado '.$passed.'/4');echo "OK | FixturePipelineTest | 4/4 PDF -> parser -> preview -> MySQL temporal -> lectura normal; diff por ruta JSON\n";
}finally{$env->close();}
