<?php
declare(strict_types=1);
require_once dirname(__DIR__,3).'/src/classes/PlanImport/bootstrap.php';require_once dirname(__DIR__,3).'/src/classes/PlanificacionPedagogica.php';require_once dirname(__DIR__,3).'/src/classes/ClaseDiaria.php';require_once __DIR__.'/../support/TestEnvironment.php';
use SiscoEdu\PlanImport\{PdfPlanImporter,PlanImportPersistence,CatalogMatcher};
function parityShape(array $plan):array{$units=[];foreach($plan['unidades'] as $u){$caps=[];foreach($u['capacidades'] as $c){$topics=[];foreach($c['temas'] as $t)$topics[]=['codigo'=>$t['codigo'],'titulo'=>$t['titulo'],'contenido'=>$t['contenido'],'horas_catedra'=>$t['horas_catedra'],'tiempo_texto'=>$t['tiempo_texto'],'fecha_texto'=>$t['fecha_texto'],'indicadores'=>array_map(static fn(array $i):array=>['codigo'=>$i['codigo'],'descripcion'=>$i['descripcion']],$t['indicadores']),'procedimientos'=>array_map(static fn(array $r):string=>$r['texto_fuente']??$r['nombre'],$t['procedimientos']),'instrumentos'=>array_map(static fn(array $r):string=>$r['texto_fuente']??$r['nombre'],$t['instrumentos'])];$caps[]=['descripcion'=>$c['descripcion'],'proceso_desarrollo'=>$c['proceso_desarrollo'],'temas'=>$topics];}$units[]=['codigo'=>$u['codigo'],'nombre'=>$u['nombre'],'descripcion'=>$u['descripcion'],'horas_catedra'=>$u['horas_catedra'],'tiempo_texto'=>$u['tiempo_texto'],'proceso_texto'=>$u['proceso_texto'],'area_transversal'=>$u['area_transversal'],'metodologia'=>$u['metodologia'],'medios_verificacion'=>$u['medios_verificacion'],'capacidades'=>$caps];}return ['competencia_general'=>$plan['competencia_general'],'competencia_especifica'=>$plan['competencia_especifica'],'unidades'=>$units];}
$env=new PlanImportTestEnvironment();
try{
    $root=dirname(__DIR__,3);if(trim((string)getenv('SISCO_PDFTOTEXT_PATH'))==='')putenv('SISCO_PDFTOTEXT_PATH=C:\\Program Files\\Git\\mingw64\\bin\\pdftotext.exe');$pdf=glob($root.'/test/fixtures/planes/*tercer curso*Administracion financiera.pdf')[0];$canonical=PdfPlanImporter::fromConfig(require $root.'/src/config/plan_import.php')->import($pdf,true);$base=$env->db->query('SELECT id_profesor,id_grado FROM asignacion_docente WHERE id_asignacion='.$env->assignment)->fetch(PDO::FETCH_ASSOC);$matter=$env->insert("INSERT INTO materias (nombre,activo) VALUES ('ADMINISTRACIÃ“N FINANCIERA MANUAL',1)",[]);$manualAssignment=$env->insert('INSERT INTO asignacion_docente (id_profesor,id_materia,id_grado,carga_horaria,anio_lectivo,activo) VALUES (?,?,?,4,2026,1)',[(int)$base['id_profesor'],$matter,(int)$base['id_grado']]);$service=new PlanificacionPedagogica($env->db,['id_usuario'=>$env->user,'rol'=>'SuperAdmin']);
    $manualId=$service->crearPlan(['id_asignacion'=>$manualAssignment,'anio'=>2026,'competencia_general'=>$canonical['metadata']['competencia_general'],'competencia_especifica'=>$canonical['metadata']['competencia_especifica']]);$m=$canonical['metadata'];$service->actualizarPlan($manualId,['competencia_general'=>$m['competencia_general'],'competencia_especifica'=>$m['competencia_especifica'],'institucion_fuente'=>$m['institucion'],'materia_fuente'=>$m['materia'],'profesor_fuente'=>$m['profesor'],'curso_fuente'=>$m['curso'],'turno_fuente'=>$m['turno'],'anio_fuente'=>$m['anio'],'dias_clase_fuente'=>$m['dias_clase']]);$catalogMaps=['procedimientos'=>[],'instrumentos'=>[]];$firstManualTopic=0;
    foreach($canonical['unidades'] as $u){$unit=$service->guardarElemento('unidad',['id_plan'=>$manualId,'codigo'=>$u['codigo'],'nombre'=>$u['nombre'],'descripcion'=>$u['descripcion'],'horas_catedra'=>$u['horas_catedra'],'tiempo_texto'=>$u['tiempo_texto'],'proceso_texto'=>$u['proceso_texto'],'proceso_inicio'=>'','proceso_fin'=>'','area_transversal'=>$u['area_transversal'],'metodologia'=>$u['metodologia'],'medios_verificacion'=>$u['medios_verificacion']]);foreach($u['capacidades'] as $c){$cap=$service->guardarElemento('capacidad',['id_unidad'=>$unit,'descripcion'=>$c['descripcion'],'proceso_desarrollo'=>$c['proceso_desarrollo']]);foreach($c['temas'] as $t){$topic=$service->guardarElemento('tema',['id_capacidad'=>$cap,'codigo'=>$t['codigo'],'titulo'=>$t['titulo'],'contenido'=>$t['contenido'],'horas_catedra'=>$t['horas_catedra'],'tiempo_texto'=>$t['tiempo_texto'],'fecha_texto'=>$t['fecha_texto']]);if(!$firstManualTopic)$firstManualTopic=$topic;foreach($t['indicadores'] as $i)$service->guardarElemento('indicador',['id_tema'=>$topic,'codigo'=>$i['codigo'],'descripcion'=>$i['descripcion']]);$ids=['procedimientos'=>[],'instrumentos'=>[]];foreach(['procedimientos'=>'procedimiento','instrumentos'=>'instrumento'] as $kind=>$singular)foreach($t[$kind.'_evaluativos'] as $text){if(!isset($catalogMaps[$kind][$text])){$created=$service->crearCatalogo($singular,$text);$catalogMaps[$kind][$text]=(int)$created[$singular==='procedimiento'?'id_procedimiento':'id_instrumento'];}$ids[$kind][]=$catalogMaps[$kind][$text];}$service->guardarEvaluacion($topic,$ids['procedimientos'],$ids['instrumentos']);}}}
    $service->guardarProgramacion(['id_tema'=>$firstManualTopic,'fecha_inicio'=>'2026-09-14','fecha_fin'=>'2026-09-14','horas_catedra_planificadas'=>4]);
    $scheduleAll=function(int $id)use($service):void{
        $rows=[];$index=0;foreach($service->obtenerPlan($id)['unidades'] as $unit)foreach($unit['capacidades'] as $cap)foreach($cap['temas'] as $topic){$date=(new DateTimeImmutable('2026-09-14'))->modify('+'.$index++.' days')->format('Y-m-d');$rows[]=['id_tema'=>(int)$topic['id_tema'],'fecha_inicio'=>$date,'fecha_fin'=>$date,'horas_catedra_planificadas'=>4];}
        $service->guardarProgramaciones($id,$rows);$service->cambiarEstado($id,'PUBLICADO');
    };
    $scheduleAll($manualId);
    $catalogs=['procedimientos'=>$env->db->query('SELECT id_procedimiento id,nombre FROM procedimientos_evaluativos WHERE activo=1')->fetchAll(PDO::FETCH_ASSOC),'instrumentos'=>$env->db->query('SELECT id_instrumento id,nombre FROM instrumentos_evaluativos WHERE activo=1')->fetchAll(PDO::FETCH_ASSOC)];$suggestions=(new CatalogMatcher())->suggestions($canonical,$catalogs);$decisions=array_map(static fn(array $s):array=>['kind'=>$s['kind'],'text'=>$s['text'],'action'=>'existing','id'=>$s['suggested_id']],$suggestions);$program=[['unidad_orden'=>1,'capacidad_orden'=>1,'tema_orden'=>1,'fecha_inicio'=>'2026-09-14','fecha_fin'=>'2026-09-14','horas_catedra_planificadas'=>4,'observaciones'=>null]];$env->db->beginTransaction();$importedId=(new PlanImportPersistence($env->db))->persist($canonical,$env->assignment,2026,$env->user,$decisions,$program);$env->db->commit();$scheduleAll($importedId);
    $manual=$service->obtenerPlan($manualId);$imported=$service->obtenerPlan($importedId);if(parityShape($manual)!=parityShape($imported))throw new RuntimeException('PlanificacionPedagogica no ofrece paridad acadÃ©mica');
    $grade=(int)$base['id_grado'];$aula=(int)$env->db->query('SELECT id_aula FROM grados WHERE id_grado='.$grade)->fetchColumn();$hm=$env->insert("INSERT INTO horarios (id_asignacion,id_grado,id_aula,dia_semana,hora_inicio,hora_fin,activo) VALUES (?,?,?,'Lunes','10:00:00','10:40:00',1)",[$manualAssignment,$grade,$aula]);$hi=$env->insert("INSERT INTO horarios (id_asignacion,id_grado,id_aula,dia_semana,hora_inicio,hora_fin,activo) VALUES (?,?,?,'Lunes','11:00:00','11:40:00',1)",[$env->assignment,$grade,$aula]);$daily=new ClaseDiaria($env->db);$cm=$daily->crearORecuperar($manualAssignment,$hm,'2026-09-14','10:00:00','10:40:00');$ci=$daily->crearORecuperar($env->assignment,$hi,'2026-09-14','11:00:00','11:40:00');$rm=$daily->informe($cm);$ri=$daily->informe($ci);foreach(['unidad','capacidad','tema','contenido'] as $key)if($rm[$key]!==$ri[$key])throw new RuntimeException('Informe diario difiere en '.$key);if(array_column($rm['indicadores'],'descripcion')!==array_column($ri['indicadores'],'descripcion'))throw new RuntimeException('clase_diaria_indicadores difiere');if((int)$rm['id_plan']!==$manualId||(int)$ri['id_plan']!==$importedId)throw new RuntimeException('ClaseDiaria no resolviÃ³ el plan correspondiente');
    $source=file_get_contents($root.'/src/classes/ClaseDiaria.php').file_get_contents($root.'/src/classes/PlanificacionPedagogica.php');if(preg_match('/planEsPdf|plan_es_pdf|esPlanPdf/i',$source))throw new RuntimeException('Rama acadÃ©mica especial para PDF');
    echo "OK | ManualImportedParityTest (manual vs PDF: PlanificacionPedagogica, programaciÃ³n, ClaseDiaria, indicadores e informe diario)\n";
}finally{$env->close();}
