<?php
declare(strict_types=1);

$root=dirname(__DIR__,3);
foreach(['/src/classes/PlanImport/Contracts/PdfTextExtractorInterface.php','/src/classes/PlanImport/Contracts/PlanFormatParserInterface.php','/src/classes/PlanImport/PlanImportException.php','/src/classes/PlanImport/ProcessRunner.php','/src/classes/PlanImport/CanonicalPlan.php','/src/classes/PlanImport/Text.php','/src/classes/PlanImport/Pdf/XpdfTableExtractor.php','/src/classes/PlanImport/Pdf/Parser/AbstractTableParser.php','/src/classes/PlanImport/Pdf/Parser/AdministracionFinancieraParser.php']as$file)require_once$root.$file;
use SiscoEdu\PlanImport\Pdf\XpdfTableExtractor;use SiscoEdu\PlanImport\Pdf\Parser\AdministracionFinancieraParser;
$config=require$root.'/src/config/plan_import.php';$config['pdftotext_binary']='C:\\Program Files\\Git\\mingw64\\bin\\pdftotext.exe';$extractor=new XpdfTableExtractor($config);$parser=new AdministracionFinancieraParser();$failures=[];
function adminAssert(bool$c,string$m):void{global$failures;if(!$c)$failures[]=$m;}
function adminCounts(array$p):array{$c=['unidades'=>0,'capacidades'=>0,'temas'=>0,'indicadores'=>0];foreach($p['unidades']as$u){$c['unidades']++;foreach($u['capacidades']as$cap){$c['capacidades']++;foreach($cap['temas']as$t){$c['temas']++;$c['indicadores']+=count($t['indicadores']);}}}return$c;}
foreach(['admin_financiera_2'=>'Plan Anual - segundo curso - BTI - Administracion financiera.pdf','admin_financiera_3'=>'Plan Anual - tercer curso - BTI - Administracion financiera.pdf']as$key=>$name){$expected=json_decode((string)file_get_contents($root.'/test/plan_parser_poc/expected/'.$key.'.expected.json'),true,512,JSON_THROW_ON_ERROR);$document=$extractor->extract($root.'/test/fixtures/planes/'.$name);$plan=$parser->parse($document);adminAssert(adminCounts($plan)===$expected['counts'],$name.' conteos');adminAssert(array_column($plan['unidades'],'codigo')===$expected['unit_codes'],$name.' códigos unidad');adminAssert(array_column($plan['unidades'],'nombre')===$expected['unit_names'],$name.' nombres unidad');adminAssert(array_column($plan['unidades'],'horas_catedra')==$expected['unit_hours'],$name.' HC');adminAssert(array_column($plan['unidades'],'proceso_texto')===$expected['unit_processes'],$name.' procesos');$hash=hash('sha256',json_encode($plan['unidades'],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR));adminAssert($hash===$expected['structure_sha256'],$name.' jerarquía completa');}
$document=$extractor->extract($root.'/test/fixtures/planes/Plan Anual - tercer curso - BTI - Administracion financiera.pdf');$document['text']=preg_replace('/1\.2/u','',(string)$document['text'],1);$mutated=$parser->parse($document);adminAssert(in_array('ORPHAN_INDICATOR',array_column($mutated['warnings'],'type'),true),'tema removido debe producir indicador huérfano');
if($failures){fwrite(STDERR,"FALLAS ADMIN PARSER:\n- ".implode("\n- ",$failures)."\n");exit(1);}echo"OK | AdministracionFinancieraParserTest (2/2 fixtures)\n";
