<?php
declare(strict_types=1);
$root=dirname(__DIR__,3);foreach(['/src/classes/PlanImport/Contracts/PdfTextExtractorInterface.php','/src/classes/PlanImport/Contracts/PlanFormatParserInterface.php','/src/classes/PlanImport/PlanImportException.php','/src/classes/PlanImport/ProcessRunner.php','/src/classes/PlanImport/CanonicalPlan.php','/src/classes/PlanImport/Text.php','/src/classes/PlanImport/Pdf/XpdfTableExtractor.php','/src/classes/PlanImport/Pdf/Parser/AbstractTableParser.php','/src/classes/PlanImport/Pdf/Parser/CompetenciaContenidoParser.php']as$file)require_once$root.$file;
use SiscoEdu\PlanImport\Pdf\XpdfTableExtractor;use SiscoEdu\PlanImport\Pdf\Parser\CompetenciaContenidoParser;
$config=require$root.'/src/config/plan_import.php';$config['pdftotext_binary']='C:\\Program Files\\Git\\mingw64\\bin\\pdftotext.exe';$extractor=new XpdfTableExtractor($config);$parser=new CompetenciaContenidoParser();$failures=[];function competenceAssert(bool$c,string$m):void{global$failures;if(!$c)$failures[]=$m;}
$name='Plan Anual - segundo curso - BCB - Excel Avanzado.pdf';$expected=json_decode((string)file_get_contents($root.'/test/plan_parser_poc/expected/competencia_contenido.expected.json'),true,512,JSON_THROW_ON_ERROR);$document=$extractor->extract($root.'/test/fixtures/planes/'.$name);$plan=$parser->parse($document);$capacities=[];$topics=[];$indicators=[];foreach($plan['unidades']as$unit)foreach($unit['capacidades']as$cap){$capacities[]=$cap;foreach($cap['temas']as$topic){$topics[]=$topic;foreach($topic['indicadores']as$indicator)$indicators[]=$indicator;}}competenceAssert(count($plan['unidades'])===2,'2 competencias/unidades');competenceAssert(count($capacities)===14,'14 capacidades');competenceAssert(count($topics)===14,'14 temas compuestos');competenceAssert(count($indicators)===47,'47 indicadores');competenceAssert(array_column($plan['unidades'],'nombre')===$expected['unit_names'],'nombres de competencias');competenceAssert(array_map(static fn(array$unit):array=>array_column($unit['capacidades'],'descripcion'),$plan['unidades'])===$expected['capacity_names_by_unit'],'capacidades por unidad');$hash=hash('sha256',json_encode($plan['unidades'],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR));competenceAssert($hash===$expected['structure_sha256'],'jerarquía completa, áreas, metodología, medios y fechas');$types=array_column($plan['warnings'],'type');sort($types);$expectedTypes=$expected['warning_types'];sort($expectedTypes);competenceAssert($types===$expectedTypes,'warnings de agrupación y mismatch');
// La capacidad repetida al inicio de la segunda página debe fusionarse y no crear una fila 15.
competenceAssert(count($capacities)===14,'continuación entre páginas fusionada');
if($failures){fwrite(STDERR,"FALLAS COMPETENCIA PARSER:\n- ".implode("\n- ",$failures)."\n");exit(1);}echo"OK | CompetenciaContenidoParserTest (2/14/47)\n";
