<?php
declare(strict_types=1);
$root=dirname(__DIR__,3);foreach(['/src/classes/PlanImport/Contracts/PdfTextExtractorInterface.php','/src/classes/PlanImport/Contracts/PlanFormatParserInterface.php','/src/classes/PlanImport/PlanImportException.php','/src/classes/PlanImport/ProcessRunner.php','/src/classes/PlanImport/CanonicalPlan.php','/src/classes/PlanImport/Text.php','/src/classes/PlanImport/PlanValidator.php','/src/classes/PlanImport/ConfidenceCalculator.php','/src/classes/PlanImport/Pdf/XpdfTableExtractor.php','/src/classes/PlanImport/Pdf/Parser/AbstractTableParser.php','/src/classes/PlanImport/Pdf/Parser/AdministracionFinancieraParser.php','/src/classes/PlanImport/Pdf/Parser/ExcelAvanzadoParser.php','/src/classes/PlanImport/Pdf/Parser/CompetenciaContenidoParser.php']as$file)require_once$root.$file;
use SiscoEdu\PlanImport\CanonicalPlan;use SiscoEdu\PlanImport\ConfidenceCalculator;use SiscoEdu\PlanImport\PlanValidator;use SiscoEdu\PlanImport\Pdf\XpdfTableExtractor;use SiscoEdu\PlanImport\Pdf\Parser\AdministracionFinancieraParser;use SiscoEdu\PlanImport\Pdf\Parser\ExcelAvanzadoParser;use SiscoEdu\PlanImport\Pdf\Parser\CompetenciaContenidoParser;
$config=require$root.'/src/config/plan_import.php';$config['pdftotext_binary']='C:\\Program Files\\Git\\mingw64\\bin\\pdftotext.exe';$extractor=new XpdfTableExtractor($config);$validator=new PlanValidator();$calculator=new ConfidenceCalculator();$failures=[];function validatorAssert(bool$c,string$m):void{global$failures;if(!$c)$failures[]=$m;}
$cases=[['admin_financiera_2','Plan Anual - segundo curso - BTI - Administracion financiera.pdf',new AdministracionFinancieraParser()],['admin_financiera_3','Plan Anual - tercer curso - BTI - Administracion financiera.pdf',new AdministracionFinancieraParser()],['excel_avanzado_3','Plan Anual - tercer curso - BCB - Excel Avanzado.pdf',new ExcelAvanzadoParser()],['competencia_contenido','Plan Anual - segundo curso - BCB - Excel Avanzado.pdf',new CompetenciaContenidoParser()]];
foreach($cases as[$key,$name,$parser]){$expected=json_decode((string)file_get_contents($root.'/test/plan_parser_poc/expected/'.$key.'.expected.json'),true,512,JSON_THROW_ON_ERROR);$plan=$validator->validate($parser->parse($extractor->extract($root.'/test/fixtures/planes/'.$name)));$confidence=$calculator->calculate($plan);validatorAssert($confidence['global']===$expected['confidence_global'],$name.' confidence '.$expected['confidence_global']);$plan['confidence']=$confidence;CanonicalPlan::assertValid($plan);}
$plan=CanonicalPlan::emptyForTest();$unit=CanonicalPlan::unit(2,'II','Unidad');$capacity=CanonicalPlan::capacity(2,'Capacidad');$topic=CanonicalPlan::topic(2,'1.1','Tema');$topic['horas_catedra']=-1;$topic['indicadores'][]=CanonicalPlan::indicator(2,'2.1.1','Indicador');$capacity['temas'][]=$topic;$unit['capacidades'][]=$capacity;$plan['unidades'][]=$unit;$plan['metadata']['anio']=1900;$bad=$validator->validate($plan);$types=array_column($bad['warnings'],'type');foreach(['MISSING_METADATA','INVALID_YEAR','INVALID_ORDER','INCOHERENT_TOPIC_CODE','INCOHERENT_INDICATOR_CODE','INVALID_HOURS']as$type)validatorAssert(in_array($type,$types,true),'corrupción debe generar '.$type);$confidence=$calculator->calculate($bad);validatorAssert($confidence['global']<100,'corrupciones deben bajar confidence');
if($failures){fwrite(STDERR,"FALLAS VALIDATOR:\n- ".implode("\n- ",$failures)."\n");exit(1);}echo"OK | PlanValidatorTest (confidence 100/100/96/93 + corruptions)\n";
